@startuml
'https://plantuml.com/sequence-diagram
title As a manager I want to close a course
autonumber

participant Manager
participant System

Manager -> System: Request to close a new course
System --> Manager : Ask to select one of the open courses
System --> Manager: Informs of Success or Failure.

@enduml