@startuml
'https://plantuml.com/sequence-diagram
title As a manager I want to open a course
autonumber

participant Manager
participant System

Manager -> System: Request to open a new course
System --> Manager : Ask to select one of the closed courses
System --> Manager: Informs of Success or Failure.

@enduml