@startuml
autonumber
actor "User" as MG

activate MG
MG -> ":System" : selects option "Create Board"
activate ":System"
":System"--> MG : asks for the necessary information (maxRows, maxColumns, Title, Column title, Row title)
deactivate ":System"
MG -> ":System": types the information
activate ":System"
":System"--> MG : informs operations success
deactivate MG
@enduml